services:
  book_api:
    image: bookserver/server:0.1
    ports:
      - 4001:4001
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOOK_PATH=/Books
    volumes:
      - type: bind
        source: /home/michael/Music/Books
        target: /Books
  book_ui:
    image: bookserver/client:0.1
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - REACT_APP_BOOK_ENDPOINT=http://localhost:4001
