services:
  book_api:
    image: goetz/bookserver:0.1
    ports:
      - 4001:4001
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOOK_PATH=/Books
    volumes:
      - type: bind
        source: /home/michael/Music/Books
        target: /Books
  # postgresql:
  #   image: postgres:13.4
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=c2sdemo
  #     - POSTGRES_USER=admin
  #     - POSTGRES_DB=observations
